[2023-06-11T11:13:35.875+0000] {taskinstance.py:1097} INFO - Dependencies not met for <TaskInstance: first_dag_02.second_task scheduled__2021-10-19T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2023-06-11T11:13:35.875579+00:00 and task will be retried at 2023-06-11T11:13:48.554797+00:00.
[2023-06-11T11:13:36.509+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2023-06-11T11:14:13.816+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_02.second_task scheduled__2021-10-19T00:00:00+00:00 [queued]>
[2023-06-11T11:14:13.901+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_02.second_task scheduled__2021-10-19T00:00:00+00:00 [queued]>
[2023-06-11T11:14:13.904+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2023-06-11T11:14:14.430+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): second_task> on 2021-10-19 00:00:00+00:00
[2023-06-11T11:14:14.548+0000] {standard_task_runner.py:57} INFO - Started process 154 to run task
[2023-06-11T11:14:14.671+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag_02', 'second_task', 'scheduled__2021-10-19T00:00:00+00:00', '--job-id', '504', '--raw', '--subdir', 'DAGS_FOLDER/First_dag.py', '--cfg-path', '/tmp/tmpvalbnfu9']
[2023-06-11T11:14:14.726+0000] {standard_task_runner.py:85} INFO - Job 504: Subtask second_task
[2023-06-11T11:14:15.812+0000] {task_command.py:410} INFO - Running <TaskInstance: first_dag_02.second_task scheduled__2021-10-19T00:00:00+00:00 [running]> on host 7586ce0070ac
[2023-06-11T11:14:18.458+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Raja' AIRFLOW_CTX_DAG_ID='first_dag_02' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-10-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-19T00:00:00+00:00'
[2023-06-11T11:14:18.547+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-11T11:14:18.589+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2023-06-11T11:14:18.651+0000] {subprocess.py:86} INFO - Output:
[2023-06-11T11:14:18.656+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task1!
[2023-06-11T11:14:18.661+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-06-11T11:14:19.442+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=first_dag_02, task_id=second_task, execution_date=20211019T000000, start_date=20230611T111413, end_date=20230611T111419
[2023-06-11T11:14:19.619+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-11T11:14:19.812+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
